package mt5

const (
	// Prefixes
	PREFIX_API    = "MT5WEBAPI%04x%04x"
	PACKET_FORMAT = "%04x%04x"

	// Configuration
	API_VERSION  = 3270
	META_SIZE    = 9
	MAX_COMMANDS = 16383

	// Authorization commands
	CMD_AUTH_START  = "AUTH_START"
	CMD_AUTH_ANSWER = "AUTH_ANSWER"

	// Trade commands
	CMD_TRADE_BALANCE = "TRADE_BALANCE"

	/* PARAMETERS */
	// Common parameters
	PARAM_RETURN_CODE = "RETCODE"

	// Authorization parameters
	PARAM_AUTH_SRV_RAND        = "SRV_RAND"
	PARAM_AUTH_SRV_RAND_ANSWER = "SRV_RAND_ANSWER"
	PARAM_AUTH_CLI_RAND        = "CLI_RAND"
	PARAM_AUTH_CLI_RAND_ANSWER = "CLI_RAND_ANSWER"
	PARAM_AUTH_CRYPT_RAND      = "CRYPT_RAND"

	// Trade parameters
	PARAM_TRADE_LOGIN        = "LOGIN"
	PARAM_TRADE_TYPE         = "TYPE"
	PARAM_TRADE_BALANCE      = "BALANCE"
	PARAM_TRADE_COMMENT      = "COMMENT"
	PARAM_TRADE_CHECK_MARGIN = "CHECK_MARGIN"
	PARAM_TRADE_TICKET       = "TICKET"

	/* CONSTANTS */
	// Trade constants
	CONST_TRADE_BALANCE = 2

	// Misc
	WORD_API             = "WebAPI"
	WORD_MANAGER         = "MANAGER"
	CRYPT_METHOD_DEFAULT = "AES256OFB"
	CRYPT_METHOD_NONE    = "NONE"
)
