package mt5

type GroupSymbol struct {
	Path                           string
	TradeMode                      string
	ExecMode                       string
	FillFlags                      string
	ExpirFlags                     string
	OrderFlags                     string
	SpreadDiff                     string
	SpreadDiffBalance              string
	StopsLevel                     string
	FreezeLevel                    string
	VolumeMin                      string
	VolumeMinExt                   string
	VolumeMax                      string
	VolumeMaxExt                   string
	VolumeStep                     string
	VolumeStepExt                  string
	VolumeLimit                    string
	VolumeLimitExt                 string
	MarginFlags                    string
	MarginInitial                  string
	MarginMaintenance              string
	MarginInitialBuy               string
	MarginInitialSell              string
	MarginInitialBuyLimit          string
	MarginInitialSellLimit         string
	MarginInitialBuyStop           string
	MarginInitialSellStop          string
	MarginInitialBuyStopLimit      string
	MarginInitialSellStopLimit     string
	MarginMaintenanceBuy           string
	MarginMaintenanceSell          string
	MarginMaintenanceBuyLimit      string
	MarginMaintenanceSellLimit     string
	MarginMaintenanceBuyStop       string
	MarginMaintenanceSellStop      string
	MarginMaintenanceBuyStopLimit  string
	MarginMaintenanceSellStopLimit string
	MarginLiquidity                string
	MarginHedged                   string
	MarginCurrency                 string
	SwapMode                       string
	SwapLong                       string
	SwapShort                      string
	Swap3Day                       string
	SwapFlags                      string
	SwapYearDay                    string
	SwapRateSunday                 string
	SwapRateMonday                 string
	SwapRateTuesday                string
	SwapRateWednesday              string
	SwapRateThursday               string
	SwapRateFriday                 string
	SwapRateSaturday               string
	REFlags                        string
	RETimeout                      string
	IEFlags                        string
	IECheckMode                    string
	IETimeout                      string
	IESlipProfit                   string
	IESlipLosing                   string
	IEVolumeMax                    string
	IEVolumeMaxExt                 string
	PermissionsFlags               string
	PermissionsBookdepth           string
}
