package mt5

type Trade struct {
	ID                   string
	Login                string
	ExternalAccount      string
	Group                string
	Symbol               string
	Digits               string
	Action               string
	TimeExpiration       string
	Type                 string
	TypeFill             string
	TypeTime             string
	Flags                string
	Volume               string
	VolumeExt            string
	Order                string
	OrderExternalID      string
	PriceOrder           string
	PriceTrigger         string
	PriceSL              string
	PriceTP              string
	PriceDeviation       string
	PriceDeviationTop    string
	PriceDeviationBottom string
	Comment              string
	ResultRetcode        string
	ResultDealer         string
	ResultDeal           string
	ResultOrder          string
	ResultVolume         string
	ResultVolumeExt      string
	ResultPrice          string
	ResultDealerBid      string
	ResultDealerAsk      string
	ResultDealerLast     string
	ResultMarketBid      string
	ResultMarketAsk      string
	ResultMarketLast     string
	ResultComment        string
	IDClient             string
	IP                   string
	SourceLogin          string
	Position             string
	PositionBy           string
	PositionExternalID   string
	PositionByExternalID string
}
